---
# This playbook deploys the whole application stack in this site.

- name: Ensure filesystem is created
  hosts: all:!master
  remote_user: root
  roles:
    - storage/format

- name: Ensure PV are created
  hosts: master
  remote_user: root
  roles:
    - storage/k8s-local-pv
    - elastic

- name: Deploy ElasticSearch
  hosts: master
  remote_user: root
  roles:
    - elastic
  tags:
    - elastic