---
# This playbook deploys the whole application stack in this site.

- name: Ensure filesystem is created
  hosts: all:!master
  become: true
  roles:
    - storage/format

- name: Ensure PV are created
  hosts: master
  become: true
  roles:
    - storage/k8s-local-pv
  tags:
    - pv

- name: Deploy ElasticSearch
  hosts: master
  become: true
  roles:
    - elastic
  tags:
    - elastic
