apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ hostvars[item].cluster_name }}-pv-{{ hostvars[item].k8s_name }}
  annotations:
        "volume.alpha.kubernetes.io/node-affinity": '{
            "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                    { "matchExpressions": [
                        { "key": "kubernetes.io/hostname",
                          "operator": "In",
                          "values": ["{{ hostvars[item].k8s_name }}"]
                        }
                    ]}
                 ]}
              }'
spec:
    capacity:
      storage: 1Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-storage
    local:
      path: {{ hostvars[item].mount }}
