---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: es-client-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      role: client

---
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: es-master-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      role: master