apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: {{ namespace }}
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  clusterIP: None
  ports:
  - name: transport
    port: 9300
