apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ namespace }}
  labels:
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    protocol: TCP
    port: 9200
    nodePort: {{ cluster_elasticsearch_port }}
  type: NodePort
