---
- name: Checking for elasticsearch.jks
  local_action:
    module: stat
    path : "{{ role_path }}/files/searchguard.key"
  register: elasticsearch_jks
  check_mode: no

- name: Checking for logging-es.jks
  local_action:
    module: stat
    path: "{{ role_path }}/files/logging-es.jks"
  register: logging_es_jks
  check_mode: no

- name: Checking for truststore.jks
  local_action:
    module: stat
    path: "{{ role_path }}//files/searchguard.truststore"
  register: truststore_file
  check_mode: no

- set_fact:
    searchguard: true
  when:
    - elasticsearch_jks.stat.exists
    - logging_es_jks.stat.exists
    - truststore_file.stat.exists

- set_fact:
    searchguard: false
  when:
    - not elasticsearch_jks.stat.exists
    - not logging_es_jks.stat.exists
    - not truststore_file.stat.exists

- debug:
    msg: "Do not generate SSL configuration"
  check_mode: no
  when:
    - not searchguard

- debug:
    msg: "Generate SSL configuration"
  check_mode: no
  when:
    - searchguard
